<?php
/**
 * Copyright 2008 Chris Abernethy
 *
 * This file is part of MicroPoll.
 * 
 * MicroPoll is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * MicroPoll is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with MicroPoll.  If not, see <http://www.gnu.org/licenses/>.
 * 
 */
?>
<a href="<?php echo attribute_escape($this->get('plugin_href')) ?>"
   title="<?php echo attribute_escape($this->get('plugin_text')) ?>">
    <?php echo wp_specialchars($this->get('plugin_text')) ?>
</a>
Plugin | Version <?php echo wp_specialchars($this->get('plugin_version')) ?> | By
<a href="<?php echo attribute_escape($this->get('author_href')) ?>"
   title="<?php echo attribute_escape($this->get('author_text')) ?>">
    <?php echo wp_specialchars($this->get('author_text')) ?>
</a>
<br/>